# Generated by Django 5.0.1 on 2026-06-27 17:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetAuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("caller_sub", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("subject", "Subject"),
                            ("colleague", "Colleague"),
                            ("public_caller", "Public caller"),
                            ("admin", "Admin"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("denied", "Denied"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "asset_id",
                    models.UUIDField(
                        help_text="Target asset UUID (404 when unknown)."
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("compliance", "Compliance"),
                            ("inventory", "Inventory"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "fields_disclosed",
                    models.JSONField(
                        default=list,
                        help_text="AssetAttribute keys returned or attempted.",
                    ),
                ),
                ("decision_reason", models.TextField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssetPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("subject", "Subject"),
                            ("colleague", "Colleague"),
                            ("public_caller", "Public caller"),
                            ("admin", "Admin"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("compliance", "Compliance"),
                            ("inventory", "Inventory"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "readable_visibilities",
                    models.JSONField(
                        default=list,
                        help_text="Visibility classes readable in this context.",
                    ),
                ),
                (
                    "writable_visibilities",
                    models.JSONField(
                        default=list,
                        help_text="Visibility classes writable in this context.",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "context"],
            },
        ),
        migrations.CreateModel(
            name="AssetAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("compliance", "Compliance"),
                            ("inventory", "Inventory"),
                        ],
                        max_length=32,
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("value", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("restricted", "Restricted"),
                            ("confidential", "Confidential"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="domain2.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["asset", "context", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="assetpolicy",
            constraint=models.UniqueConstraint(
                fields=("role", "context"), name="unique_asset_role_context"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetattribute",
            constraint=models.UniqueConstraint(
                fields=("asset", "context", "key"), name="unique_asset_context_key"
            ),
        ),
    ]
