# Generated by Django 5.2.15 on 2026-06-21 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("legal", "Legal"),
                            ("professional", "Professional"),
                            ("personal", "Personal"),
                            ("online", "Online"),
                        ],
                        max_length=32,
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("value", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("restricted", "Restricted"),
                            ("confidential", "Confidential"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_fields",
                        to="domain.person",
                    ),
                ),
            ],
            options={
                "ordering": ["person", "context", "key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person", "context", "key"),
                        name="unique_person_context_key",
                    )
                ],
            },
        ),
    ]
