# Generated by Django 5.2.15 on 2026-06-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0002_profile_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("subject", "Subject"),
                            ("colleague", "Colleague"),
                            ("public_caller", "Public caller"),
                            ("admin", "Admin"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("legal", "Legal"),
                            ("professional", "Professional"),
                            ("personal", "Personal"),
                            ("online", "Online"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "readable_visibilities",
                    models.JSONField(
                        default=list,
                        help_text="Visibility classes readable in this context.",
                    ),
                ),
                (
                    "writable_visibilities",
                    models.JSONField(
                        default=list,
                        help_text="Visibility classes writable in this context.",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "context"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "context"), name="unique_role_context"
                    )
                ],
            },
        ),
    ]
