# Generated by Django 5.2.15 on 2026-06-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0003_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("caller_sub", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("subject", "Subject"),
                            ("colleague", "Colleague"),
                            ("public_caller", "Public caller"),
                            ("admin", "Admin"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("denied", "Denied"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("legal", "Legal"),
                            ("professional", "Professional"),
                            ("personal", "Personal"),
                            ("online", "Online"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "fields_disclosed",
                    models.JSONField(
                        default=list,
                        help_text="ProfileField keys returned or attempted.",
                    ),
                ),
                ("decision_reason", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="domain.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
