# Generated by Django 5.2.15 on 2026-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0005_audit_entry_person_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="owner_sub",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Identity 'sub' that owns this record. Empty means unowned: no "
                    "subject-role caller can match it (deny by default)."
                ),
                max_length=255,
            ),
        ),
    ]
